samples: create BigQuery subscription
googleapis/python-pubsub pull request #722
Opened 2022-06-22 00:21 UTC by kamalaboulhosn

2022-06-23 15:58 UTC, anguillanneuf requested changes
Mostly LGTM. Resource creation+deletion should be moved out of the test.

2022-07-06 17:29 UTC, kamalaboulhosn commented on samples/snippets/subscriber_test.py
> +    client.delete_dataset(dataset)
Done.

2022-07-06 17:34 UTC, anguillanneuf approved these changes
The samples tests failures seem unrelated. @acocuzzo to investigate. #730 may be the fix.

2022-07-07 18:10 UTC, acocuzzo commented on samples/snippets/subscriber_test.py
> +    underscored_version = PY_VERSION.replace(".", "_")
This unused variable is causing linter failure, please remove

2022-07-07 18:31 UTC, merged